// generated by newgenasym  Wed Aug 12 01:49:08 2015


module max3205 (ep, gnd, \i/o_1 , \i/o_2 , \i/o_3 , \i/o_4 , \i/o_5 , \i/o_6 , nc1, nc2,
        nc3, nc4, nc5, nc6, nc7, nc8, vcc);
    input ep;
    input gnd;
    inout \i/o_1 ;
    inout \i/o_2 ;
    inout \i/o_3 ;
    inout \i/o_4 ;
    inout \i/o_5 ;
    inout \i/o_6 ;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout nc8;
    input vcc;


    initial
        begin
        end

endmodule
