-- generated by newgenasym Wed Aug 12 01:49:08 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max3205 is
    port (    
	EP:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\i/o_1\:   INOUT  STD_LOGIC;    
	\i/o_2\:   INOUT  STD_LOGIC;    
	\i/o_3\:   INOUT  STD_LOGIC;    
	\i/o_4\:   INOUT  STD_LOGIC;    
	\i/o_5\:   INOUT  STD_LOGIC;    
	\i/o_6\:   INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	NC6:       INOUT  STD_LOGIC;    
	NC7:       INOUT  STD_LOGIC;    
	NC8:       INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end max3205;
