// generated by newgenasym  Thu Feb 11 16:08:57 2016


module battery_holder (\1 , \1_1 , \2 , \2_1 , \3 );
    inout \1 ;
    inout \1_1 ;
    inout \2 ;
    inout \2_1 ;
    inout \3 ;


    initial
        begin
        end

endmodule
