-- generated by newgenasym Thu Feb 11 16:08:57 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity battery_holder is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\1_1\:     INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\2_1\:     INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end battery_holder;
