// generated by newgenasym  Mon May 02 20:24:01 2016


module \74c2t45  (a1, a2, b1, b2, dir, gnd, vcca, vccb);
    output a1;
    output a2;
    input b1;
    input b2;
    input dir;
    input gnd;
    input vcca;
    input vccb;


    initial
        begin
        end

endmodule
