-- generated by newgenasym Mon May 02 20:24:01 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74c2t45\ is
    port (    
	A1:        OUT    STD_LOGIC;    
	A2:        OUT    STD_LOGIC;    
	B1:        IN     STD_LOGIC;    
	B2:        IN     STD_LOGIC;    
	DIR:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCCA:      IN     STD_LOGIC;    
	VCCB:      IN     STD_LOGIC);
end \74c2t45\;
