// generated by newgenasym  Tue May 26 14:43:59 2015


module \898-xx-xxx-90-310000  (a, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9, b1, b10, b11,
        b12, b2, b3, b4, b5, b6, b7, b8, b9, shield_1, shield_2,
        shield_3, shield_4, shield_5, shield_6, shield_7, shield_8);
    parameter    size = 1;
    inout [size-1:0] a;
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout b1;
    inout b10;
    inout b11;
    inout b12;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout b9;
    inout shield_1;
    inout shield_2;
    inout shield_3;
    inout shield_4;
    inout shield_5;
    inout shield_6;
    inout shield_7;
    inout shield_8;


    initial
        begin
        end

endmodule
