// generated by newgenasym  Tue May 14 02:35:07 2013


module cap_4p (\1 , \2 , \3 , \4 , a, b, g1, g2);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout a;
    inout b;
    input g1;
    input g2;


    initial
        begin
        end

endmodule
