-- generated by newgenasym Tue May 14 02:35:07 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cap_4p is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	G1:        IN     STD_LOGIC;    
	G2:        IN     STD_LOGIC);
end cap_4p;
