// generated by newgenasym  Wed Sep 02 16:19:08 2015


module max8880 (ep, fb, gnd, in, out, pok, \shdn* );
    inout ep;
    input fb;
    input gnd;
    input in;
    output out;
    inout pok;
    input \shdn* ;


    initial
        begin
        end

endmodule
