-- generated by newgenasym Wed Sep 02 16:19:08 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max8880 is
    port (    
	EP:        INOUT  STD_LOGIC;    
	FB:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	POK:       INOUT  STD_LOGIC;    
	\shdn*\:   IN     STD_LOGIC);
end max8880;
