-- generated by newgenasym Mon Jul 06 13:34:36 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity em9301 is
    port (    
	ANTN:      IN     STD_LOGIC;    
	ANTP:      IN     STD_LOGIC;    
	AVDD_PA:   IN     STD_LOGIC;    
	AVSS_PA:   IN     STD_LOGIC;    
	AVSS_PLL1: IN     STD_LOGIC;    
	AVSS_PLL2: IN     STD_LOGIC;    
	AVSS_PLL3: IN     STD_LOGIC;    
	AVSS_RF:   IN     STD_LOGIC;    
	BIAS_R:    INOUT  STD_LOGIC;    
	EP:        IN     STD_LOGIC;    
	IRQ:       OUT    STD_LOGIC;    
	RST:       IN     STD_LOGIC;    
	SEL:       IN     STD_LOGIC;    
	SPI_SCK:   IN     STD_LOGIC;    
	SW_DCDC:   IN     STD_LOGIC;    
	\uart_rx/spi_mosi\: IN     STD_LOGIC;    
	\uart_tx/spi_miso\: OUT    STD_LOGIC;    
	VBAT:      INOUT  STD_LOGIC;    
	VCC1:      IN     STD_LOGIC;    
	VCC2:      IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VSS:       IN     STD_LOGIC;    
	VSS_DCDC:  IN     STD_LOGIC;    
	\wu/csn\:  IN     STD_LOGIC;    
	XTAL1:     INOUT  STD_LOGIC;    
	XTAL2:     INOUT  STD_LOGIC);
end em9301;
