// generated by newgenasym  Tue Aug 18 16:51:17 2015


module lsm6ds3 (cs, gnd_1, gnd_2, int1, int2, nc, ocs, scl, scx, sda, \sdo/sa0 ,
        sdx, vdd, vddio);
    input cs;
    input gnd_1;
    input gnd_2;
    input int1;
    input int2;
    inout nc;
    input ocs;
    input scl;
    input scx;
    inout sda;
    output \sdo/sa0 ;
    inout sdx;
    input vdd;
    input vddio;


    initial
        begin
        end

endmodule
