-- generated by newgenasym Tue Aug 18 16:51:17 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lsm6ds3 is
    port (    
	CS:        IN     STD_LOGIC;    
	GND_1:     IN     STD_LOGIC;    
	GND_2:     IN     STD_LOGIC;    
	INT1:      IN     STD_LOGIC;    
	INT2:      IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	OCS:       IN     STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SCX:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	\sdo/sa0\: OUT    STD_LOGIC;    
	SDX:       INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VDDIO:     IN     STD_LOGIC);
end lsm6ds3;
