// generated by newgenasym  Tue Oct 27 13:51:35 2015


module s25fs256s (\cs# , ep, \io3/reset# , sck, \si/io0 , \so/io1 , vdd, vss, \wp#/io2 );
    input \cs# ;
    input ep;
    input \io3/reset# ;
    input sck;
    inout \si/io0 ;
    inout \so/io1 ;
    input vdd;
    input vss;
    input \wp#/io2 ;


    initial
        begin
        end

endmodule
