-- generated by newgenasym Tue Oct 27 13:51:35 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity s25fs256s is
    port (    
	\cs#\:     IN     STD_LOGIC;    
	EP:        IN     STD_LOGIC;    
	\io3/reset#\: IN     STD_LOGIC;    
	SCK:       IN     STD_LOGIC;    
	\si/io0\:  INOUT  STD_LOGIC;    
	\so/io1\:  INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VSS:       IN     STD_LOGIC;    
	\wp#/io2\: IN     STD_LOGIC);
end s25fs256s;
