// generated by newgenasym  Tue May 03 02:19:45 2016


module max30205 (a0, a1, a2, ep, gnd, os, scl, sda, vdd);
    input a0;
    input a1;
    input a2;
    input ep;
    input gnd;
    output os;
    input scl;
    inout sda;
    input vdd;


    initial
        begin
        end

endmodule
