-- generated by newgenasym Tue May 03 02:19:45 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max30205 is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	EP:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	OS:        OUT    STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end max30205;
