// generated by newgenasym  Thu Apr 28 16:02:42 2016


module xtal (\1 , \2 , \3 , \4 , gnd, gnd1, gnd2, \i.c._1 , \i.c._2 , nc, nc1, nc2, oe,
        out, p1, p2, p3, vcc, vio);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    input gnd;
    input gnd1;
    output gnd2;
    inout \i.c._1 ;
    inout \i.c._2 ;
    inout nc;
    inout nc1;
    inout nc2;
    input oe;
    output out;
    input p1;
    output p2;
    inout p3;
    input vcc;
    input vio;


    initial
        begin
        end

endmodule
