-- generated by newgenasym Thu Apr 28 16:02:42 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xtal is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      OUT    STD_LOGIC;    
	\i.c._1\:  INOUT  STD_LOGIC;    
	\i.c._2\:  INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	OE:        IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	P1:        IN     STD_LOGIC;    
	P2:        OUT    STD_LOGIC;    
	P3:        INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VIO:       IN     STD_LOGIC);
end xtal;
