// generated by newgenasym  Mon Mar 30 18:38:40 2015


module fdfme2p823zt (a, d_1, d_2, g, k_1, k_2, nc, s);
    inout a;
    inout d_1;
    inout d_2;
    inout g;
    inout k_1;
    inout k_2;
    inout nc;
    inout s;


    initial
        begin
        end

endmodule
