-- generated by newgenasym Mon Mar 30 18:38:40 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fdfme2p823zt is
    port (    
	A:         INOUT  STD_LOGIC;    
	D_1:       INOUT  STD_LOGIC;    
	D_2:       INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	K_1:       INOUT  STD_LOGIC;    
	K_2:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC);
end fdfme2p823zt;
