// generated by newgenasym  Thu Feb 12 16:24:27 2015


module lis2dh (cs, gnd_1, gnd_2, gnd_3, int1, int2, res_1, res_2, res_3,
        \scl/spc , \sda/sdi/sdo , \sdo/sa0 , vdd, vdd_io);
    input cs;
    input gnd_1;
    input gnd_2;
    input gnd_3;
    output int1;
    output int2;
    inout res_1;
    inout res_2;
    inout res_3;
    input \scl/spc ;
    inout \sda/sdi/sdo ;
    output \sdo/sa0 ;
    input vdd;
    input vdd_io;


    initial
        begin
        end

endmodule
