-- generated by newgenasym Thu Feb 12 16:24:27 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LIS2DH is
    port (    
	CS:        IN     STD_LOGIC;    
	GND_1:     IN     STD_LOGIC;    
	GND_2:     IN     STD_LOGIC;    
	GND_3:     IN     STD_LOGIC;    
	INT1:      OUT    STD_LOGIC;    
	INT2:      OUT    STD_LOGIC;    
	RES_1:     INOUT  STD_LOGIC;    
	RES_2:     INOUT  STD_LOGIC;    
	RES_3:     INOUT  STD_LOGIC;    
	\scl/spc\: IN     STD_LOGIC;    
	\sda/sdi/sdo\: INOUT  STD_LOGIC;    
	\sdo/sa0\: OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VDD_IO:    IN     STD_LOGIC);
end LIS2DH;
