// generated by newgenasym  Thu Aug 06 13:59:18 2015


module \741g97  (a, b, c, gnd, vcc, y);
    input a;
    input b;
    input c;
    input gnd;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
