-- generated by newgenasym Thu Aug 06 13:59:18 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \741g97\ is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	C:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end \741g97\;
