// generated by newgenasym  Tue May 17 20:13:38 2016


module tran_nch_3p (d, d1, g, g1, s);
    inout d;
    inout d1;
    inout g;
    inout g1;
    inout s;


    initial
        begin
        end

endmodule
