-- generated by newgenasym Tue May 17 20:13:38 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tran_nch_3p is
    port (    
	D:         INOUT  STD_LOGIC;    
	D1:        INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	G1:        INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC);
end tran_nch_3p;
