// generated by newgenasym  Wed Nov 26 15:59:30 2014


module max30101 (\/int , g_drv, gnd, ir_drv, nc_1, nc_2, nc_3, pgnd, r_drv, scl,
        sda, vdd, \vled+_1 , \vled+_2 );
    input \/int ;
    inout g_drv;
    input gnd;
    inout ir_drv;
    inout nc_1;
    inout nc_2;
    inout nc_3;
    input pgnd;
    inout r_drv;
    input scl;
    inout sda;
    input vdd;
    input \vled+_1 ;
    input \vled+_2 ;


    initial
        begin
        end

endmodule
