-- generated by newgenasym Wed Nov 26 15:59:30 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max30101 is
    port (    
	\/int\:    IN     STD_LOGIC;    
	G_DRV:     INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	IR_DRV:    INOUT  STD_LOGIC;    
	NC_1:      INOUT  STD_LOGIC;    
	NC_2:      INOUT  STD_LOGIC;    
	NC_3:      INOUT  STD_LOGIC;    
	PGND:      IN     STD_LOGIC;    
	R_DRV:     INOUT  STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	\vled+_1\: IN     STD_LOGIC;    
	\vled+_2\: IN     STD_LOGIC);
end max30101;
