// generated by newgenasym  Wed Apr 06 09:48:23 2016


module ek_max30033 (ep, gnd1, gnd2, gnd3, gnd_1, gnd_2, gnd_3, in1, in2, in3, nc1,
        nc2, nc_1, nc_2, vin1, vin2, vin3);
    input ep;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd_1;
    input gnd_2;
    input gnd_3;
    input in1;
    input in2;
    input in3;
    inout nc1;
    inout nc2;
    inout nc_1;
    inout nc_2;
    input vin1;
    input vin2;
    input vin3;


    initial
        begin
        end

endmodule
