// generated by newgenasym  Wed Jun 15 07:18:33 2016


module induct (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
