-- generated by newgenasym Wed Jun 15 07:18:33 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity induct is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end induct;
