// generated by newgenasym  Tue May 03 20:16:46 2016


module max4995 (\/flag , \/on , gnd, in, in_1, in_2, nc_1, nc_2, on, out, out_1,
        out_2, seti);
    inout \/flag ;
    input \/on ;
    input gnd;
    input in;
    input in_1;
    input in_2;
    inout nc_1;
    inout nc_2;
    input on;
    output out;
    output out_1;
    output out_2;
    inout seti;


    initial
        begin
        end

endmodule
