-- generated by newgenasym Tue May 03 20:16:46 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max4995 is
    port (    
	\/flag\:   INOUT  STD_LOGIC;    
	\/on\:     IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	IN_1:      IN     STD_LOGIC;    
	IN_2:      IN     STD_LOGIC;    
	NC_1:      INOUT  STD_LOGIC;    
	NC_2:      INOUT  STD_LOGIC;    
	\on\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	OUT_1:     OUT    STD_LOGIC;    
	OUT_2:     OUT    STD_LOGIC;    
	SETI:      INOUT  STD_LOGIC);
end max4995;
