// generated by newgenasym  Wed Jul 15 16:35:54 2015


module max14720 (bin, blx, bout, cap, gnd_1, gnd_2, gnd_3, gnd_4, gnd_5, hvilx,
        hvin, hvolx, hvout, \kin# , \kout# , lin, lout, mon, mpc, \rst# , scl,
        sda, swin, swout, vcc);
    input bin;
    input blx;
    output bout;
    input cap;
    input gnd_1;
    input gnd_2;
    input gnd_3;
    input gnd_4;
    input gnd_5;
    input hvilx;
    input hvin;
    input hvolx;
    output hvout;
    input \kin# ;
    output \kout# ;
    input lin;
    output lout;
    output mon;
    input mpc;
    output \rst# ;
    input scl;
    input sda;
    input swin;
    output swout;
    input vcc;


    initial
        begin
        end

endmodule
