-- generated by newgenasym Wed Jul 15 16:35:54 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max14720 is
    port (    
	BIN:       IN     STD_LOGIC;    
	BLX:       IN     STD_LOGIC;    
	BOUT:      OUT    STD_LOGIC;    
	CAP:       IN     STD_LOGIC;    
	GND_1:     IN     STD_LOGIC;    
	GND_2:     IN     STD_LOGIC;    
	GND_3:     IN     STD_LOGIC;    
	GND_4:     IN     STD_LOGIC;    
	GND_5:     IN     STD_LOGIC;    
	HVILX:     IN     STD_LOGIC;    
	HVIN:      IN     STD_LOGIC;    
	HVOLX:     IN     STD_LOGIC;    
	HVOUT:     OUT    STD_LOGIC;    
	\kin#\:    IN     STD_LOGIC;    
	\kout#\:   OUT    STD_LOGIC;    
	LIN:       IN     STD_LOGIC;    
	LOUT:      OUT    STD_LOGIC;    
	MON:       OUT    STD_LOGIC;    
	MPC:       IN     STD_LOGIC;    
	\rst#\:    OUT    STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       IN     STD_LOGIC;    
	SWIN:      IN     STD_LOGIC;    
	SWOUT:     OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end max14720;
