// generated by newgenasym  Tue Jun 14 01:50:03 2016


module ek_max30003 (agnd_1, agnd_2, agnd_3, \aout/atbp , avdd, bin, bip, capn,
        capp, cpll, csb, dgnd, drvn, drvp, dvdd, ecgn, ecgp, ep, fclk,
        int2b, intb, ovdd, \rbias/atbm , sclk, sdi, sdo, vbg, vcm, vref);
    inout agnd_1;
    inout agnd_2;
    inout agnd_3;
    inout \aout/atbp ;
    inout avdd;
    inout bin;
    inout bip;
    inout capn;
    inout capp;
    inout cpll;
    inout csb;
    inout dgnd;
    inout drvn;
    inout drvp;
    inout dvdd;
    inout ecgn;
    inout ecgp;
    inout ep;
    inout fclk;
    inout int2b;
    inout intb;
    inout ovdd;
    inout \rbias/atbm ;
    inout sclk;
    inout sdi;
    inout sdo;
    inout vbg;
    inout vcm;
    inout vref;


    initial
        begin
        end

endmodule
