-- generated by newgenasym Tue Jun 14 01:50:03 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ek_max30003 is
    port (    
	AGND_1:    INOUT  STD_LOGIC;    
	AGND_2:    INOUT  STD_LOGIC;    
	AGND_3:    INOUT  STD_LOGIC;    
	\aout/atbp\: INOUT  STD_LOGIC;    
	AVDD:      INOUT  STD_LOGIC;    
	BIN:       INOUT  STD_LOGIC;    
	BIP:       INOUT  STD_LOGIC;    
	CAPN:      INOUT  STD_LOGIC;    
	CAPP:      INOUT  STD_LOGIC;    
	CPLL:      INOUT  STD_LOGIC;    
	CSB:       INOUT  STD_LOGIC;    
	DGND:      INOUT  STD_LOGIC;    
	DRVN:      INOUT  STD_LOGIC;    
	DRVP:      INOUT  STD_LOGIC;    
	DVDD:      INOUT  STD_LOGIC;    
	ECGN:      INOUT  STD_LOGIC;    
	ECGP:      INOUT  STD_LOGIC;    
	EP:        INOUT  STD_LOGIC;    
	FCLK:      INOUT  STD_LOGIC;    
	INT2B:     INOUT  STD_LOGIC;    
	INTB:      INOUT  STD_LOGIC;    
	OVDD:      INOUT  STD_LOGIC;    
	\rbias/atbm\: INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC;    
	SDI:       INOUT  STD_LOGIC;    
	SDO:       INOUT  STD_LOGIC;    
	VBG:       INOUT  STD_LOGIC;    
	VCM:       INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end ek_max30003;
