// generated by newgenasym  Mon Mar 30 14:38:09 2015


module \evp-aaxxxx  (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
