// generated by newgenasym  Thu Feb 26 10:52:37 2015


module \2450at42b100e  (\input , nc_1, nc_2, nc_3);
    inout \input ;
    inout nc_1;
    inout nc_2;
    inout nc_3;


    initial
        begin
        end

endmodule
