-- generated by newgenasym Thu Feb 26 10:52:37 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \2450at42b100e\ is
    port (    
	INPUT:     INOUT  STD_LOGIC;    
	NC_1:      INOUT  STD_LOGIC;    
	NC_2:      INOUT  STD_LOGIC;    
	NC_3:      INOUT  STD_LOGIC);
end \2450at42b100e\;
