// generated by newgenasym  Thu May 14 16:39:22 2015


module bmp280 (csb, gnd1, gnd2, sck, sdi, sdo, vdd, vddio);
    input csb;
    input gnd1;
    input gnd2;
    input sck;
    input sdi;
    output sdo;
    input vdd;
    input vddio;


    initial
        begin
        end

endmodule
