-- generated by newgenasym Thu May 14 16:39:22 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bmp280 is
    port (    
	CSB:       IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	SCK:       IN     STD_LOGIC;    
	SDI:       IN     STD_LOGIC;    
	SDO:       OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VDDIO:     IN     STD_LOGIC);
end bmp280;
