// generated by newgenasym  Tue Jul 07 11:07:44 2015


module tran_dch_8p (\d1-1 , \d1-2 , d1_1, d1_2, d1a, d1b, \d2-1 , \d2-2 , d2_1, d2_2, d2a,
        d2b, g1, g2, s1, s2);
    inout \d1-1 ;
    inout \d1-2 ;
    inout d1_1;
    inout d1_2;
    inout d1a;
    inout d1b;
    inout \d2-1 ;
    inout \d2-2 ;
    inout d2_1;
    inout d2_2;
    inout d2a;
    inout d2b;
    inout g1;
    inout g2;
    inout s1;
    inout s2;


    initial
        begin
        end

endmodule
