-- generated by newgenasym Tue Jul 07 11:07:44 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tran_dch_8p is
    port (    
	\d1-1\:    INOUT  STD_LOGIC;    
	\d1-2\:    INOUT  STD_LOGIC;    
	D1_1:      INOUT  STD_LOGIC;    
	D1_2:      INOUT  STD_LOGIC;    
	D1A:       INOUT  STD_LOGIC;    
	D1B:       INOUT  STD_LOGIC;    
	\d2-1\:    INOUT  STD_LOGIC;    
	\d2-2\:    INOUT  STD_LOGIC;    
	D2_1:      INOUT  STD_LOGIC;    
	D2_2:      INOUT  STD_LOGIC;    
	D2A:       INOUT  STD_LOGIC;    
	D2B:       INOUT  STD_LOGIC;    
	G1:        INOUT  STD_LOGIC;    
	G2:        INOUT  STD_LOGIC;    
	S1:        INOUT  STD_LOGIC;    
	S2:        INOUT  STD_LOGIC);
end tran_dch_8p;
