// generated by newgenasym  Thu Jun 23 16:41:20 2011


module max8881 (fb, gnd, in, out, pok, \shdn* );
    input fb;
    input gnd;
    input in;
    output out;
    inout pok;
    input \shdn* ;


    initial
        begin
        end

endmodule
