-- generated by newgenasym Thu Jun 23 16:41:20 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max8881 is
    port (    
	FB:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	POK:       INOUT  STD_LOGIC;    
	\shdn*\:   IN     STD_LOGIC);
end max8881;
