// generated by newgenasym  Tue May 31 12:05:23 2016


module res_smd (\1 , \2 , \3 , tab);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    input tab;


    initial
        begin
        end

endmodule
