-- generated by newgenasym Tue May 31 12:05:23 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res_smd is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	TAB:       IN     STD_LOGIC);
end res_smd;
