// generated by newgenasym  Fri Apr 29 19:08:05 2016


module led (a, a1, a2, b, b1, b2, thermal);
    inout a;
    inout a1;
    inout a2;
    inout b;
    inout b1;
    inout b2;
    inout thermal;


    initial
        begin
        end

endmodule
