-- generated by newgenasym Fri Apr 29 19:08:05 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led is
    port (    
	A:         INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	THERMAL:   INOUT  STD_LOGIC);
end led;
