// generated by newgenasym  Thu Jun 04 11:48:17 2015


module max4741 (com1, com2, gnd, in1, in2, no1, no2, \v+ );
    inout com1;
    inout com2;
    input gnd;
    inout in1;
    inout in2;
    inout no1;
    inout no2;
    input \v+ ;


    initial
        begin
        end

endmodule
