-- generated by newgenasym Thu Jun 04 11:48:17 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max4741 is
    port (    
	COM1:      INOUT  STD_LOGIC;    
	COM2:      INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	NO1:       INOUT  STD_LOGIC;    
	NO2:       INOUT  STD_LOGIC;    
	\v+\:      IN     STD_LOGIC);
end max4741;
