// generated by newgenasym  Tue Feb 24 17:02:49 2015


module balun (bp1, bp2, gnd1, gnd2, gnd_1, gnd_2, gnd_3, in, nc, out1, out2,
        up);
    input bp1;
    input bp2;
    input gnd1;
    input gnd2;
    input gnd_1;
    input gnd_2;
    input gnd_3;
    input in;
    inout nc;
    output out1;
    output out2;
    output up;


    initial
        begin
        end

endmodule
