-- generated by newgenasym Tue Feb 24 17:02:49 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity balun is
    port (    
	BP1:       IN     STD_LOGIC;    
	BP2:       IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND_1:     IN     STD_LOGIC;    
	GND_2:     IN     STD_LOGIC;    
	GND_3:     IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	OUT1:      OUT    STD_LOGIC;    
	OUT2:      OUT    STD_LOGIC;    
	UP:        OUT    STD_LOGIC);
end balun;
