// generated by newgenasym  Thu Aug 13 10:44:45 2015


module sn74avc4t234 (gnd, in_1, in_2, in_3, in_4, out_1, out_2, out_3, out_4, vcca,
        vccb);
    input gnd;
    input in_1;
    input in_2;
    input in_3;
    input in_4;
    output out_1;
    output out_2;
    output out_3;
    output out_4;
    input vcca;
    input vccb;


    initial
        begin
        end

endmodule
