-- generated by newgenasym Thu Aug 13 10:44:45 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74avc4t234 is
    port (    
	GND:       IN     STD_LOGIC;    
	IN_1:      IN     STD_LOGIC;    
	IN_2:      IN     STD_LOGIC;    
	IN_3:      IN     STD_LOGIC;    
	IN_4:      IN     STD_LOGIC;    
	OUT_1:     OUT    STD_LOGIC;    
	OUT_2:     OUT    STD_LOGIC;    
	OUT_3:     OUT    STD_LOGIC;    
	OUT_4:     OUT    STD_LOGIC;    
	VCCA:      IN     STD_LOGIC;    
	VCCB:      IN     STD_LOGIC);
end sn74avc4t234;
