// generated by newgenasym  Wed Dec 02 06:04:39 2015


module max32620 (\32kin , \32kout , ain0, ain1, ain2, ain3, dm, dp, ep, nc1, nc10,
        nc11, nc12, nc13, nc14, nc15, nc16, nc17, nc18, nc19, nc2, nc20,
        nc3, nc4, nc5, nc6, nc7, nc8, nc9, p0_0, p0_1, p0_2, p0_3, p0_4,
        p0_5, p0_6, p0_7, p1_0, p1_1, p1_2, p1_3, p1_4, p1_5, p1_6,
        p1_7, p2_0, p2_1, p2_2, p2_3, p2_4, p2_5, p2_6, p2_7, p3_0,
        p3_1, p3_2, p3_3, p3_4, p3_5, p3_6, p3_7, p4_0, p4_1, p4_2,
        p4_3, p4_4, p4_5, p4_6, p4_7, p5_0, p5_1, p5_2, p5_3, p5_4,
        p5_5, p5_6, p5_7, p6_0, rstn, srstn, tck, tdi, tdo, tms, vdd12,
        vdd18_1, vdd18_2, vdd18_3, vdd18_4, vdda, vddb, vref, vrtc,
        vss_1, vss_2, vss_3, vss_4, vss_5, vss_6, vss_7, vssa);
    inout \32kin ;
    inout \32kout ;
    inout ain0;
    inout ain1;
    inout ain2;
    inout ain3;
    inout dm;
    inout dp;
    inout ep;
    inout nc1;
    inout nc10;
    inout nc11;
    inout nc12;
    inout nc13;
    inout nc14;
    inout nc15;
    inout nc16;
    inout nc17;
    inout nc18;
    inout nc19;
    inout nc2;
    inout nc20;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout nc8;
    inout nc9;
    inout p0_0;
    inout p0_1;
    inout p0_2;
    inout p0_3;
    inout p0_4;
    inout p0_5;
    inout p0_6;
    inout p0_7;
    inout p1_0;
    inout p1_1;
    inout p1_2;
    inout p1_3;
    inout p1_4;
    inout p1_5;
    inout p1_6;
    inout p1_7;
    inout p2_0;
    inout p2_1;
    inout p2_2;
    inout p2_3;
    inout p2_4;
    inout p2_5;
    inout p2_6;
    inout p2_7;
    inout p3_0;
    inout p3_1;
    inout p3_2;
    inout p3_3;
    inout p3_4;
    inout p3_5;
    inout p3_6;
    inout p3_7;
    inout p4_0;
    inout p4_1;
    inout p4_2;
    inout p4_3;
    inout p4_4;
    inout p4_5;
    inout p4_6;
    inout p4_7;
    inout p5_0;
    inout p5_1;
    inout p5_2;
    inout p5_3;
    inout p5_4;
    inout p5_5;
    inout p5_6;
    inout p5_7;
    inout p6_0;
    inout rstn;
    inout srstn;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    inout vdd12;
    inout vdd18_1;
    inout vdd18_2;
    inout vdd18_3;
    inout vdd18_4;
    inout vdda;
    inout vddb;
    inout vref;
    inout vrtc;
    inout vss_1;
    inout vss_2;
    inout vss_3;
    inout vss_4;
    inout vss_5;
    inout vss_6;
    inout vss_7;
    inout vssa;


    initial
        begin
        end

endmodule
