-- generated by newgenasym Wed Jun 15 14:46:21 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cap_pol is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end cap_pol;
