// generated by newgenasym  Tue Jul 07 10:30:42 2015


module max9064 (gnd1, gnd2, in, out, vcc);
    input gnd1;
    input gnd2;
    input in;
    output out;
    input vcc;


    initial
        begin
        end

endmodule
