-- generated by newgenasym Tue Jul 07 10:30:42 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max9064 is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end max9064;
