// generated by newgenasym  Fri Feb 07 14:24:26 2014


module nlas4684 (com1, com2, gnd, in1, in2, \n.c.1 , \n.c.2 , \n.o.1 , \n.o.2 , vcc);
    input com1;
    input com2;
    input gnd;
    inout in1;
    inout in2;
    output \n.c.1 ;
    output \n.c.2 ;
    output \n.o.1 ;
    output \n.o.2 ;
    input vcc;


    initial
        begin
        end

endmodule
