-- generated by newgenasym Fri Feb 07 14:24:26 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity nlas4684 is
    port (    
	COM1:      IN     STD_LOGIC;    
	COM2:      IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	\n.c.1\:   OUT    STD_LOGIC;    
	\n.c.2\:   OUT    STD_LOGIC;    
	\n.o.1\:   OUT    STD_LOGIC;    
	\n.o.2\:   OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end nlas4684;
